// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt7Mlcyw9gFj_55Jsauq6MyV94kSUMl4s',
    appId: '1:184366190632:web:8812e6cf6b9deabcff651d',
    messagingSenderId: '184366190632',
    projectId: 'smart-707fa',
    authDomain: 'smart-707fa.firebaseapp.com',
    storageBucket: 'smart-707fa.firebasestorage.app',
    measurementId: 'G-FSN5LTV444',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnNWAr9NpDq0_D8qr5F3is6oZSXbvr1A',
    appId: '1:184366190632:android:116e03f01824db99ff651d',
    messagingSenderId: '184366190632',
    projectId: 'smart-707fa',
    storageBucket: 'smart-707fa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt7Mlcyw9gFj_55Jsauq6MyV94kSUMl4s',
    appId: '1:184366190632:web:fea143d65d2b5a32ff651d',
    messagingSenderId: '184366190632',
    projectId: 'smart-707fa',
    authDomain: 'smart-707fa.firebaseapp.com',
    storageBucket: 'smart-707fa.firebasestorage.app',
    measurementId: 'G-VNDW2FL4T6',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1G1FfHRYCiKxCTqig2mOX_OFQ07XeBQg',
    appId: '1:184366190632:ios:8f5e117283977caaff651d',
    messagingSenderId: '184366190632',
    projectId: 'smart-707fa',
    storageBucket: 'smart-707fa.firebasestorage.app',
    iosBundleId: 'com.example.smartHospital',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1G1FfHRYCiKxCTqig2mOX_OFQ07XeBQg',
    appId: '1:184366190632:ios:8f5e117283977caaff651d',
    messagingSenderId: '184366190632',
    projectId: 'smart-707fa',
    storageBucket: 'smart-707fa.firebasestorage.app',
    iosBundleId: 'com.example.smartHospital',
  );
}
